version: "3"

services:
  baby-front:
    restart: always
    image: nginx
    container_name: baby-manage-front
    ports:
      - "8080:8080"
      - "80:80"
      - "8443:443"
    volumes:
      - "./dist:/usr/share/nginx/html"
      - "./default.conf:/etc/nginx/conf.d/default.conf"