version: "3"

services:
  baby-front:
    restart: always
    image: baby-front
    container_name: baby-front
    ports:
      - "8080:8080"
      - "80:80"
      - "8443:443"
    volumes:
      - "./default.conf:/etc/nginx/conf.d/default.conf"